//
//  IonIcons.swift
//  HackerNews
//
//  Created by Mihail Cristian Dumitru on 10/30/16.
//  Copyright © 2016 Null. All rights reserved.
//

import UIKit

class IonIcon {

    static let kFontName = "Ionicons"
    private static let kFontIconSizeOffset: CGFloat = 4

    static func icon(type: IonIconType, ofSize size: CGFloat, color: UIColor = ThemeManager.current.other) -> NSMutableAttributedString {
        return NSMutableAttributedString(
            string: type.rawValue,
            attributes: [
                NSFontAttributeName: UIFont.ionIconFont(ofSize: size + kFontIconSizeOffset),
                NSForegroundColorAttributeName: color
            ])
    }

    static func constraint(label: UILabel, toSize size: CGSize, maxFontSize: CGFloat, minFontSize: CGFloat) -> CGFloat {
        // Set the frame of the label to the targeted rectangle
        let rect = CGRect(x: 0, y: 0, width: size.width, height: size.height)
        label.frame = rect

        // Try all font sizes from largest to smallest font size
        var fontSize = maxFontSize

        // Fit label width wize
        let constraintSize = CGSize(width: label.frame.width, height: CGFloat.greatestFiniteMagnitude)

        repeat {
            // Set current font size
            label.font = UIFont(name: label.font.fontName, size: fontSize)

            // Find label size for current font size
            let textRect = ((label.text ?? "") as NSString).boundingRect(
                with: constraintSize,
                options: [.usesFontLeading],
                attributes: [NSFontAttributeName: label.font],
                context: nil)

            // Done, if created label is within target size
            if textRect.height <= label.frame.size.height {
                break
            }

            // decrease the font size and try again
            fontSize -= 2
        } while fontSize > minFontSize

        return fontSize
    }

    static func image(iconType type: IonIconType, size: CGFloat = 32, color: UIColor) -> UIImage? {
        return UIImage.image(withIconType: type, iconColor: color, andSize: CGSize(width: size, height: size))
    }

}

extension IonIcon {
    static func titleIcon(type: IonIconType, color: UIColor = ThemeManager.current.other) -> NSMutableAttributedString {
        return self.icon(type: type, ofSize: FontManager.currentFont.titleSize, color: color)
    }

    static func textIcon(type: IonIconType, color: UIColor = ThemeManager.current.other) -> NSMutableAttributedString {
        return self.icon(type: type, ofSize: FontManager.currentFont.textSize, color: color)
    }

    static func subtitleIcon(type: IonIconType, color: UIColor = ThemeManager.current.other) -> NSMutableAttributedString {
        return self.icon(type: type, ofSize: FontManager.currentFont.subtitleSize, color: color)
    }
}

extension UIImage {

    static func image(withIconType type: IonIconType, backgroundColor: UIColor = UIColor.clear, iconColor: UIColor = UIColor.white, andSize size: CGSize) -> UIImage? {

        UIGraphicsBeginImageContextWithOptions(size, false, 0)

        var textRect = CGRect.zero
        textRect.size = size

        // rectangle
        let path = UIBezierPath(rect: textRect)
        backgroundColor.setFill()
        path.fill()

        // text
        var fontSize = size.width
        let font = UIFont.ionIconFont(ofSize: fontSize)

        let label = UILabel()
        label.font = font
        label.text = type.rawValue
        fontSize = IonIcon.constraint(
            label: label,
            toSize: size,
            maxFontSize: 50,
            minFontSize: 5)
        iconColor.setFill()

        let style = NSMutableParagraphStyle()
        style.alignment = .center
        (type.rawValue as NSString).draw(
            in: textRect,
            withAttributes: [
                NSFontAttributeName: font,
                NSForegroundColorAttributeName: iconColor,
                NSBackgroundColorAttributeName: backgroundColor,
                NSParagraphStyleAttributeName: style
            ])

        // return image
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return image
    }

}

extension UIFont {
    static func ionIconFont(ofSize size: CGFloat) -> UIFont {
        return UIFont(name: IonIcon.kFontName, size: size)!
    }
}

enum IonIconType: String {
    case ion_alert = "\u{f101}"
    case ion_alert_circled = "\u{f100}"
    case ion_android_add = "\u{f2c7}"
    case ion_android_add_circle = "\u{f359}"
    case ion_android_alarm_clock = "\u{f35a}"
    case ion_android_alert = "\u{f35b}"
    case ion_android_apps = "\u{f35c}"
    case ion_android_archive = "\u{f2c9}"
    case ion_android_arrow_back = "\u{f2ca}"
    case ion_android_arrow_down = "\u{f35d}"
    case ion_android_arrow_dropdown = "\u{f35f}"
    case ion_android_arrow_dropdown_circle = "\u{f35e}"
    case ion_android_arrow_dropleft = "\u{f361}"
    case ion_android_arrow_dropleft_circle = "\u{f360}"
    case ion_android_arrow_dropright = "\u{f363}"
    case ion_android_arrow_dropright_circle = "\u{f362}"
    case ion_android_arrow_dropup = "\u{f365}"
    case ion_android_arrow_dropup_circle = "\u{f364}"
    case ion_android_arrow_forward = "\u{f30f}"
    case ion_android_arrow_up = "\u{f366}"
    case ion_android_attach = "\u{f367}"
    case ion_android_bar = "\u{f368}"
    case ion_android_bicycle = "\u{f369}"
    case ion_android_boat = "\u{f36a}"
    case ion_android_bookmark = "\u{f36b}"
    case ion_android_bulb = "\u{f36c}"
    case ion_android_bus = "\u{f36d}"
    case ion_android_calendar = "\u{f2d1}"
    case ion_android_call = "\u{f2d2}"
    case ion_android_camera = "\u{f2d3}"
    case ion_android_cancel = "\u{f36e}"
    case ion_android_car = "\u{f36f}"
    case ion_android_cart = "\u{f370}"
    case ion_android_chat = "\u{f2d4}"
    case ion_android_checkbox = "\u{f374}"
    case ion_android_checkbox_blank = "\u{f371}"
    case ion_android_checkbox_outline = "\u{f373}"
    case ion_android_checkbox_outline_blank = "\u{f372}"
    case ion_android_checkmark_circle = "\u{f375}"
    case ion_android_clipboard = "\u{f376}"
    case ion_android_close = "\u{f2d7}"
    case ion_android_cloud = "\u{f37a}"
    case ion_android_cloud_circle = "\u{f377}"
    case ion_android_cloud_done = "\u{f378}"
    case ion_android_cloud_outline = "\u{f379}"
    case ion_android_color_palette = "\u{f37b}"
    case ion_android_compass = "\u{f37c}"
    case ion_android_contact = "\u{f2d8}"
    case ion_android_contacts = "\u{f2d9}"
    case ion_android_contract = "\u{f37d}"
    case ion_android_create = "\u{f37e}"
    case ion_android_delete = "\u{f37f}"
    case ion_android_desktop = "\u{f380}"
    case ion_android_document = "\u{f381}"
    case ion_android_done = "\u{f383}"
    case ion_android_done_all = "\u{f382}"
    case ion_android_download = "\u{f2dd}"
    case ion_android_drafts = "\u{f384}"
    case ion_android_exit = "\u{f385}"
    case ion_android_expand = "\u{f386}"
    case ion_android_favorite = "\u{f388}"
    case ion_android_favorite_outline = "\u{f387}"
    case ion_android_film = "\u{f389}"
    case ion_android_folder = "\u{f2e0}"
    case ion_android_folder_open = "\u{f38a}"
    case ion_android_funnel = "\u{f38b}"
    case ion_android_globe = "\u{f38c}"
    case ion_android_hand = "\u{f2e3}"
    case ion_android_hangout = "\u{f38d}"
    case ion_android_happy = "\u{f38e}"
    case ion_android_home = "\u{f38f}"
    case ion_android_image = "\u{f2e4}"
    case ion_android_laptop = "\u{f390}"
    case ion_android_list = "\u{f391}"
    case ion_android_locate = "\u{f2e9}"
    case ion_android_lock = "\u{f392}"
    case ion_android_mail = "\u{f2eb}"
    case ion_android_map = "\u{f393}"
    case ion_android_menu = "\u{f394}"
    case ion_android_microphone = "\u{f2ec}"
    case ion_android_microphone_off = "\u{f395}"
    case ion_android_more_horizontal = "\u{f396}"
    case ion_android_more_vertical = "\u{f397}"
    case ion_android_navigate = "\u{f398}"
    case ion_android_notifications = "\u{f39b}"
    case ion_android_notifications_none = "\u{f399}"
    case ion_android_notifications_off = "\u{f39a}"
    case ion_android_open = "\u{f39c}"
    case ion_android_options = "\u{f39d}"
    case ion_android_people = "\u{f39e}"
    case ion_android_person = "\u{f3a0}"
    case ion_android_person_add = "\u{f39f}"
    case ion_android_phone_landscape = "\u{f3a1}"
    case ion_android_phone_portrait = "\u{f3a2}"
    case ion_android_pin = "\u{f3a3}"
    case ion_android_plane = "\u{f3a4}"
    case ion_android_playstore = "\u{f2f0}"
    case ion_android_print = "\u{f3a5}"
    case ion_android_radio_button_off = "\u{f3a6}"
    case ion_android_radio_button_on = "\u{f3a7}"
    case ion_android_refresh = "\u{f3a8}"
    case ion_android_remove = "\u{f2f4}"
    case ion_android_remove_circle = "\u{f3a9}"
    case ion_android_restaurant = "\u{f3aa}"
    case ion_android_sad = "\u{f3ab}"
    case ion_android_search = "\u{f2f5}"
    case ion_android_send = "\u{f2f6}"
    case ion_android_settings = "\u{f2f7}"
    case ion_android_share = "\u{f2f8}"
    case ion_android_share_alt = "\u{f3ac}"
    case ion_android_star = "\u{f2fc}"
    case ion_android_star_half = "\u{f3ad}"
    case ion_android_star_outline = "\u{f3ae}"
    case ion_android_stopwatch = "\u{f2fd}"
    case ion_android_subway = "\u{f3af}"
    case ion_android_sunny = "\u{f3b0}"
    case ion_android_sync = "\u{f3b1}"
    case ion_android_textsms = "\u{f3b2}"
    case ion_android_time = "\u{f3b3}"
    case ion_android_train = "\u{f3b4}"
    case ion_android_unlock = "\u{f3b5}"
    case ion_android_upload = "\u{f3b6}"
    case ion_android_volume_down = "\u{f3b7}"
    case ion_android_volume_mute = "\u{f3b8}"
    case ion_android_volume_off = "\u{f3b9}"
    case ion_android_volume_up = "\u{f3ba}"
    case ion_android_walk = "\u{f3bb}"
    case ion_android_warning = "\u{f3bc}"
    case ion_android_watch = "\u{f3bd}"
    case ion_android_wifi = "\u{f305}"
    case ion_aperture = "\u{f313}"
    case ion_archive = "\u{f102}"
    case ion_arrow_down_a = "\u{f103}"
    case ion_arrow_down_b = "\u{f104}"
    case ion_arrow_down_c = "\u{f105}"
    case ion_arrow_expand = "\u{f25e}"
    case ion_arrow_graph_down_left = "\u{f25f}"
    case ion_arrow_graph_down_right = "\u{f260}"
    case ion_arrow_graph_up_left = "\u{f261}"
    case ion_arrow_graph_up_right = "\u{f262}"
    case ion_arrow_left_a = "\u{f106}"
    case ion_arrow_left_b = "\u{f107}"
    case ion_arrow_left_c = "\u{f108}"
    case ion_arrow_move = "\u{f263}"
    case ion_arrow_resize = "\u{f264}"
    case ion_arrow_return_left = "\u{f265}"
    case ion_arrow_return_right = "\u{f266}"
    case ion_arrow_right_a = "\u{f109}"
    case ion_arrow_right_b = "\u{f10a}"
    case ion_arrow_right_c = "\u{f10b}"
    case ion_arrow_shrink = "\u{f267}"
    case ion_arrow_swap = "\u{f268}"
    case ion_arrow_up_a = "\u{f10c}"
    case ion_arrow_up_b = "\u{f10d}"
    case ion_arrow_up_c = "\u{f10e}"
    case ion_asterisk = "\u{f314}"
    case ion_at = "\u{f10f}"
    case ion_backspace = "\u{f3bf}"
    case ion_backspace_outline = "\u{f3be}"
    case ion_bag = "\u{f110}"
    case ion_battery_charging = "\u{f111}"
    case ion_battery_empty = "\u{f112}"
    case ion_battery_full = "\u{f113}"
    case ion_battery_half = "\u{f114}"
    case ion_battery_low = "\u{f115}"
    case ion_beaker = "\u{f269}"
    case ion_beer = "\u{f26a}"
    case ion_bluetooth = "\u{f116}"
    case ion_bonfire = "\u{f315}"
    case ion_bookmark = "\u{f26b}"
    case ion_bowtie = "\u{f3c0}"
    case ion_briefcase = "\u{f26c}"
    case ion_bug = "\u{f2be}"
    case ion_calculator = "\u{f26d}"
    case ion_calendar = "\u{f117}"
    case ion_camera = "\u{f118}"
    case ion_card = "\u{f119}"
    case ion_cash = "\u{f316}"
    case ion_chatbox = "\u{f11b}"
    case ion_chatbox_working = "\u{f11a}"
    case ion_chatboxes = "\u{f11c}"
    case ion_chatbubble = "\u{f11e}"
    case ion_chatbubble_working = "\u{f11d}"
    case ion_chatbubbles = "\u{f11f}"
    case ion_checkmark = "\u{f122}"
    case ion_checkmark_circled = "\u{f120}"
    case ion_checkmark_round = "\u{f121}"
    case ion_chevron_down = "\u{f123}"
    case ion_chevron_left = "\u{f124}"
    case ion_chevron_right = "\u{f125}"
    case ion_chevron_up = "\u{f126}"
    case ion_clipboard = "\u{f127}"
    case ion_clock = "\u{f26e}"
    case ion_close = "\u{f12a}"
    case ion_close_circled = "\u{f128}"
    case ion_close_round = "\u{f129}"
    case ion_closed_captioning = "\u{f317}"
    case ion_cloud = "\u{f12b}"
    case ion_code = "\u{f271}"
    case ion_code_download = "\u{f26f}"
    case ion_code_working = "\u{f270}"
    case ion_coffee = "\u{f272}"
    case ion_compass = "\u{f273}"
    case ion_compose = "\u{f12c}"
    case ion_connection_bars = "\u{f274}"
    case ion_contrast = "\u{f275}"
    case ion_crop = "\u{f3c1}"
    case ion_cube = "\u{f318}"
    case ion_disc = "\u{f12d}"
    case ion_document = "\u{f12f}"
    case ion_document_text = "\u{f12e}"
    case ion_drag = "\u{f130}"
    case ion_earth = "\u{f276}"
    case ion_easel = "\u{f3c2}"
    case ion_edit = "\u{f2bf}"
    case ion_egg = "\u{f277}"
    case ion_eject = "\u{f131}"
    case ion_email = "\u{f132}"
    case ion_email_unread = "\u{f3c3}"
    case ion_erlenmeyer_flask = "\u{f3c5}"
    case ion_erlenmeyer_flask_bubbles = "\u{f3c4}"
    case ion_eye = "\u{f133}"
    case ion_eye_disabled = "\u{f306}"
    case ion_female = "\u{f278}"
    case ion_filing = "\u{f134}"
    case ion_film_marker = "\u{f135}"
    case ion_fireball = "\u{f319}"
    case ion_flag = "\u{f279}"
    case ion_flame = "\u{f31a}"
    case ion_flash = "\u{f137}"
    case ion_flash_off = "\u{f136}"
    case ion_folder = "\u{f139}"
    case ion_fork = "\u{f27a}"
    case ion_fork_repo = "\u{f2c0}"
    case ion_forward = "\u{f13a}"
    case ion_funnel = "\u{f31b}"
    case ion_gear_a = "\u{f13d}"
    case ion_gear_b = "\u{f13e}"
    case ion_grid = "\u{f13f}"
    case ion_hammer = "\u{f27b}"
    case ion_happy = "\u{f31c}"
    case ion_happy_outline = "\u{f3c6}"
    case ion_headphone = "\u{f140}"
    case ion_heart = "\u{f141}"
    case ion_heart_broken = "\u{f31d}"
    case ion_help = "\u{f143}"
    case ion_help_buoy = "\u{f27c}"
    case ion_help_circled = "\u{f142}"
    case ion_home = "\u{f144}"
    case ion_icecream = "\u{f27d}"
    case ion_image = "\u{f147}"
    case ion_images = "\u{f148}"
    case ion_information = "\u{f14a}"
    case ion_information_circled = "\u{f149}"
    case ion_ionic = "\u{f14b}"
    case ion_ios_alarm = "\u{f3c8}"
    case ion_ios_alarm_outline = "\u{f3c7}"
    case ion_ios_albums = "\u{f3ca}"
    case ion_ios_albums_outline = "\u{f3c9}"
    case ion_ios_americanfootball = "\u{f3cc}"
    case ion_ios_americanfootball_outline = "\u{f3cb}"
    case ion_ios_analytics = "\u{f3ce}"
    case ion_ios_analytics_outline = "\u{f3cd}"
    case ion_ios_arrow_back = "\u{f3cf}"
    case ion_ios_arrow_down = "\u{f3d0}"
    case ion_ios_arrow_forward = "\u{f3d1}"
    case ion_ios_arrow_left = "\u{f3d2}"
    case ion_ios_arrow_right = "\u{f3d3}"
    case ion_ios_arrow_thin_down = "\u{f3d4}"
    case ion_ios_arrow_thin_left = "\u{f3d5}"
    case ion_ios_arrow_thin_right = "\u{f3d6}"
    case ion_ios_arrow_thin_up = "\u{f3d7}"
    case ion_ios_arrow_up = "\u{f3d8}"
    case ion_ios_at = "\u{f3da}"
    case ion_ios_at_outline = "\u{f3d9}"
    case ion_ios_barcode = "\u{f3dc}"
    case ion_ios_barcode_outline = "\u{f3db}"
    case ion_ios_baseball = "\u{f3de}"
    case ion_ios_baseball_outline = "\u{f3dd}"
    case ion_ios_basketball = "\u{f3e0}"
    case ion_ios_basketball_outline = "\u{f3df}"
    case ion_ios_bell = "\u{f3e2}"
    case ion_ios_bell_outline = "\u{f3e1}"
    case ion_ios_body = "\u{f3e4}"
    case ion_ios_body_outline = "\u{f3e3}"
    case ion_ios_bolt = "\u{f3e6}"
    case ion_ios_bolt_outline = "\u{f3e5}"
    case ion_ios_book = "\u{f3e8}"
    case ion_ios_book_outline = "\u{f3e7}"
    case ion_ios_bookmarks = "\u{f3ea}"
    case ion_ios_bookmarks_outline = "\u{f3e9}"
    case ion_ios_box = "\u{f3ec}"
    case ion_ios_box_outline = "\u{f3eb}"
    case ion_ios_briefcase = "\u{f3ee}"
    case ion_ios_briefcase_outline = "\u{f3ed}"
    case ion_ios_browsers = "\u{f3f0}"
    case ion_ios_browsers_outline = "\u{f3ef}"
    case ion_ios_calculator = "\u{f3f2}"
    case ion_ios_calculator_outline = "\u{f3f1}"
    case ion_ios_calendar = "\u{f3f4}"
    case ion_ios_calendar_outline = "\u{f3f3}"
    case ion_ios_camera = "\u{f3f6}"
    case ion_ios_camera_outline = "\u{f3f5}"
    case ion_ios_cart = "\u{f3f8}"
    case ion_ios_cart_outline = "\u{f3f7}"
    case ion_ios_chatboxes = "\u{f3fa}"
    case ion_ios_chatboxes_outline = "\u{f3f9}"
    case ion_ios_chatbubble = "\u{f3fc}"
    case ion_ios_chatbubble_outline = "\u{f3fb}"
    case ion_ios_checkmark = "\u{f3ff}"
    case ion_ios_checkmark_empty = "\u{f3fd}"
    case ion_ios_checkmark_outline = "\u{f3fe}"
    case ion_ios_circle_filled = "\u{f400}"
    case ion_ios_circle_outline = "\u{f401}"
    case ion_ios_clock = "\u{f403}"
    case ion_ios_clock_outline = "\u{f402}"
    case ion_ios_close = "\u{f406}"
    case ion_ios_close_empty = "\u{f404}"
    case ion_ios_close_outline = "\u{f405}"
    case ion_ios_cloud = "\u{f40c}"
    case ion_ios_cloud_download = "\u{f408}"
    case ion_ios_cloud_download_outline = "\u{f407}"
    case ion_ios_cloud_outline = "\u{f409}"
    case ion_ios_cloud_upload = "\u{f40b}"
    case ion_ios_cloud_upload_outline = "\u{f40a}"
    case ion_ios_cloudy = "\u{f410}"
    case ion_ios_cloudy_night = "\u{f40e}"
    case ion_ios_cloudy_night_outline = "\u{f40d}"
    case ion_ios_cloudy_outline = "\u{f40f}"
    case ion_ios_cog = "\u{f412}"
    case ion_ios_cog_outline = "\u{f411}"
    case ion_ios_color_filter = "\u{f414}"
    case ion_ios_color_filter_outline = "\u{f413}"
    case ion_ios_color_wand = "\u{f416}"
    case ion_ios_color_wand_outline = "\u{f415}"
    case ion_ios_compose = "\u{f418}"
    case ion_ios_compose_outline = "\u{f417}"
    case ion_ios_contact = "\u{f41a}"
    case ion_ios_contact_outline = "\u{f419}"
    case ion_ios_copy = "\u{f41c}"
    case ion_ios_copy_outline = "\u{f41b}"
    case ion_ios_crop = "\u{f41e}"
    case ion_ios_crop_strong = "\u{f41d}"
    case ion_ios_download = "\u{f420}"
    case ion_ios_download_outline = "\u{f41f}"
    case ion_ios_drag = "\u{f421}"
    case ion_ios_email = "\u{f423}"
    case ion_ios_email_outline = "\u{f422}"
    case ion_ios_eye = "\u{f425}"
    case ion_ios_eye_outline = "\u{f424}"
    case ion_ios_fastforward = "\u{f427}"
    case ion_ios_fastforward_outline = "\u{f426}"
    case ion_ios_filing = "\u{f429}"
    case ion_ios_filing_outline = "\u{f428}"
    case ion_ios_film = "\u{f42b}"
    case ion_ios_film_outline = "\u{f42a}"
    case ion_ios_flag = "\u{f42d}"
    case ion_ios_flag_outline = "\u{f42c}"
    case ion_ios_flame = "\u{f42f}"
    case ion_ios_flame_outline = "\u{f42e}"
    case ion_ios_flask = "\u{f431}"
    case ion_ios_flask_outline = "\u{f430}"
    case ion_ios_flower = "\u{f433}"
    case ion_ios_flower_outline = "\u{f432}"
    case ion_ios_folder = "\u{f435}"
    case ion_ios_folder_outline = "\u{f434}"
    case ion_ios_football = "\u{f437}"
    case ion_ios_football_outline = "\u{f436}"
    case ion_ios_game_controller_a = "\u{f439}"
    case ion_ios_game_controller_a_outline = "\u{f438}"
    case ion_ios_game_controller_b = "\u{f43b}"
    case ion_ios_game_controller_b_outline = "\u{f43a}"
    case ion_ios_gear = "\u{f43d}"
    case ion_ios_gear_outline = "\u{f43c}"
    case ion_ios_glasses = "\u{f43f}"
    case ion_ios_glasses_outline = "\u{f43e}"
    case ion_ios_grid_view = "\u{f441}"
    case ion_ios_grid_view_outline = "\u{f440}"
    case ion_ios_heart = "\u{f443}"
    case ion_ios_heart_outline = "\u{f442}"
    case ion_ios_help = "\u{f446}"
    case ion_ios_help_empty = "\u{f444}"
    case ion_ios_help_outline = "\u{f445}"
    case ion_ios_home = "\u{f448}"
    case ion_ios_home_outline = "\u{f447}"
    case ion_ios_infinite = "\u{f44a}"
    case ion_ios_infinite_outline = "\u{f449}"
    case ion_ios_information = "\u{f44d}"
    case ion_ios_information_empty = "\u{f44b}"
    case ion_ios_information_outline = "\u{f44c}"
    case ion_ios_ionic_outline = "\u{f44e}"
    case ion_ios_keypad = "\u{f450}"
    case ion_ios_keypad_outline = "\u{f44f}"
    case ion_ios_lightbulb = "\u{f452}"
    case ion_ios_lightbulb_outline = "\u{f451}"
    case ion_ios_list = "\u{f454}"
    case ion_ios_list_outline = "\u{f453}"
    case ion_ios_location = "\u{f456}"
    case ion_ios_location_outline = "\u{f455}"
    case ion_ios_locked = "\u{f458}"
    case ion_ios_locked_outline = "\u{f457}"
    case ion_ios_loop = "\u{f45a}"
    case ion_ios_loop_strong = "\u{f459}"
    case ion_ios_medical = "\u{f45c}"
    case ion_ios_medical_outline = "\u{f45b}"
    case ion_ios_medkit = "\u{f45e}"
    case ion_ios_medkit_outline = "\u{f45d}"
    case ion_ios_mic = "\u{f461}"
    case ion_ios_mic_off = "\u{f45f}"
    case ion_ios_mic_outline = "\u{f460}"
    case ion_ios_minus = "\u{f464}"
    case ion_ios_minus_empty = "\u{f462}"
    case ion_ios_minus_outline = "\u{f463}"
    case ion_ios_monitor = "\u{f466}"
    case ion_ios_monitor_outline = "\u{f465}"
    case ion_ios_moon = "\u{f468}"
    case ion_ios_moon_outline = "\u{f467}"
    case ion_ios_more = "\u{f46a}"
    case ion_ios_more_outline = "\u{f469}"
    case ion_ios_musical_note = "\u{f46b}"
    case ion_ios_musical_notes = "\u{f46c}"
    case ion_ios_navigate = "\u{f46e}"
    case ion_ios_navigate_outline = "\u{f46d}"
    case ion_ios_nutrition = "\u{f470}"
    case ion_ios_nutrition_outline = "\u{f46f}"
    case ion_ios_paper = "\u{f472}"
    case ion_ios_paper_outline = "\u{f471}"
    case ion_ios_paperplane = "\u{f474}"
    case ion_ios_paperplane_outline = "\u{f473}"
    case ion_ios_partlysunny = "\u{f476}"
    case ion_ios_partlysunny_outline = "\u{f475}"
    case ion_ios_pause = "\u{f478}"
    case ion_ios_pause_outline = "\u{f477}"
    case ion_ios_paw = "\u{f47a}"
    case ion_ios_paw_outline = "\u{f479}"
    case ion_ios_people = "\u{f47c}"
    case ion_ios_people_outline = "\u{f47b}"
    case ion_ios_person = "\u{f47e}"
    case ion_ios_person_outline = "\u{f47d}"
    case ion_ios_personadd = "\u{f480}"
    case ion_ios_personadd_outline = "\u{f47f}"
    case ion_ios_photos = "\u{f482}"
    case ion_ios_photos_outline = "\u{f481}"
    case ion_ios_pie = "\u{f484}"
    case ion_ios_pie_outline = "\u{f483}"
    case ion_ios_pint = "\u{f486}"
    case ion_ios_pint_outline = "\u{f485}"
    case ion_ios_play = "\u{f488}"
    case ion_ios_play_outline = "\u{f487}"
    case ion_ios_plus = "\u{f48b}"
    case ion_ios_plus_empty = "\u{f489}"
    case ion_ios_plus_outline = "\u{f48a}"
    case ion_ios_pricetag = "\u{f48d}"
    case ion_ios_pricetag_outline = "\u{f48c}"
    case ion_ios_pricetags = "\u{f48f}"
    case ion_ios_pricetags_outline = "\u{f48e}"
    case ion_ios_printer = "\u{f491}"
    case ion_ios_printer_outline = "\u{f490}"
    case ion_ios_pulse = "\u{f493}"
    case ion_ios_pulse_strong = "\u{f492}"
    case ion_ios_rainy = "\u{f495}"
    case ion_ios_rainy_outline = "\u{f494}"
    case ion_ios_recording = "\u{f497}"
    case ion_ios_recording_outline = "\u{f496}"
    case ion_ios_redo = "\u{f499}"
    case ion_ios_redo_outline = "\u{f498}"
    case ion_ios_refresh = "\u{f49c}"
    case ion_ios_refresh_empty = "\u{f49a}"
    case ion_ios_refresh_outline = "\u{f49b}"
    case ion_ios_reload = "\u{f49d}"
    case ion_ios_reverse_camera = "\u{f49f}"
    case ion_ios_reverse_camera_outline = "\u{f49e}"
    case ion_ios_rewind = "\u{f4a1}"
    case ion_ios_rewind_outline = "\u{f4a0}"
    case ion_ios_rose = "\u{f4a3}"
    case ion_ios_rose_outline = "\u{f4a2}"
    case ion_ios_search = "\u{f4a5}"
    case ion_ios_search_strong = "\u{f4a4}"
    case ion_ios_settings = "\u{f4a7}"
    case ion_ios_settings_strong = "\u{f4a6}"
    case ion_ios_shuffle = "\u{f4a9}"
    case ion_ios_shuffle_strong = "\u{f4a8}"
    case ion_ios_skipbackward = "\u{f4ab}"
    case ion_ios_skipbackward_outline = "\u{f4aa}"
    case ion_ios_skipforward = "\u{f4ad}"
    case ion_ios_skipforward_outline = "\u{f4ac}"
    case ion_ios_snowy = "\u{f4ae}"
    case ion_ios_speedometer = "\u{f4b0}"
    case ion_ios_speedometer_outline = "\u{f4af}"
    case ion_ios_star = "\u{f4b3}"
    case ion_ios_star_half = "\u{f4b1}"
    case ion_ios_star_outline = "\u{f4b2}"
    case ion_ios_stopwatch = "\u{f4b5}"
    case ion_ios_stopwatch_outline = "\u{f4b4}"
    case ion_ios_sunny = "\u{f4b7}"
    case ion_ios_sunny_outline = "\u{f4b6}"
    case ion_ios_telephone = "\u{f4b9}"
    case ion_ios_telephone_outline = "\u{f4b8}"
    case ion_ios_tennisball = "\u{f4bb}"
    case ion_ios_tennisball_outline = "\u{f4ba}"
    case ion_ios_thunderstorm = "\u{f4bd}"
    case ion_ios_thunderstorm_outline = "\u{f4bc}"
    case ion_ios_time = "\u{f4bf}"
    case ion_ios_time_outline = "\u{f4be}"
    case ion_ios_timer = "\u{f4c1}"
    case ion_ios_timer_outline = "\u{f4c0}"
    case ion_ios_toggle = "\u{f4c3}"
    case ion_ios_toggle_outline = "\u{f4c2}"
    case ion_ios_trash = "\u{f4c5}"
    case ion_ios_trash_outline = "\u{f4c4}"
    case ion_ios_undo = "\u{f4c7}"
    case ion_ios_undo_outline = "\u{f4c6}"
    case ion_ios_unlocked = "\u{f4c9}"
    case ion_ios_unlocked_outline = "\u{f4c8}"
    case ion_ios_upload = "\u{f4cb}"
    case ion_ios_upload_outline = "\u{f4ca}"
    case ion_ios_videocam = "\u{f4cd}"
    case ion_ios_videocam_outline = "\u{f4cc}"
    case ion_ios_volume_high = "\u{f4ce}"
    case ion_ios_volume_low = "\u{f4cf}"
    case ion_ios_wineglass = "\u{f4d1}"
    case ion_ios_wineglass_outline = "\u{f4d0}"
    case ion_ios_world = "\u{f4d3}"
    case ion_ios_world_outline = "\u{f4d2}"
    case ion_ipad = "\u{f1f9}"
    case ion_iphone = "\u{f1fa}"
    case ion_ipod = "\u{f1fb}"
    case ion_jet = "\u{f295}"
    case ion_key = "\u{f296}"
    case ion_knife = "\u{f297}"
    case ion_laptop = "\u{f1fc}"
    case ion_leaf = "\u{f1fd}"
    case ion_levels = "\u{f298}"
    case ion_lightbulb = "\u{f299}"
    case ion_link = "\u{f1fe}"
    case ion_load_a = "\u{f29a}"
    case ion_load_b = "\u{f29b}"
    case ion_load_c = "\u{f29c}"
    case ion_load_d = "\u{f29d}"
    case ion_location = "\u{f1ff}"
    case ion_lock_combination = "\u{f4d4}"
    case ion_locked = "\u{f200}"
    case ion_log_in = "\u{f29e}"
    case ion_log_out = "\u{f29f}"
    case ion_loop = "\u{f201}"
    case ion_magnet = "\u{f2a0}"
    case ion_male = "\u{f2a1}"
    case ion_man = "\u{f202}"
    case ion_map = "\u{f203}"
    case ion_medkit = "\u{f2a2}"
    case ion_merge = "\u{f33f}"
    case ion_mic_a = "\u{f204}"
    case ion_mic_b = "\u{f205}"
    case ion_mic_c = "\u{f206}"
    case ion_minus = "\u{f209}"
    case ion_minus_circled = "\u{f207}"
    case ion_minus_round = "\u{f208}"
    case ion_model_s = "\u{f2c1}"
    case ion_monitor = "\u{f20a}"
    case ion_more = "\u{f20b}"
    case ion_mouse = "\u{f340}"
    case ion_music_note = "\u{f20c}"
    case ion_navicon = "\u{f20e}"
    case ion_navicon_round = "\u{f20d}"
    case ion_navigate = "\u{f2a3}"
    case ion_network = "\u{f341}"
    case ion_no_smoking = "\u{f2c2}"
    case ion_nuclear = "\u{f2a4}"
    case ion_outlet = "\u{f342}"
    case ion_paintbrush = "\u{f4d5}"
    case ion_paintbucket = "\u{f4d6}"
    case ion_paper_airplane = "\u{f2c3}"
    case ion_paperclip = "\u{f20f}"
    case ion_pause = "\u{f210}"
    case ion_person = "\u{f213}"
    case ion_person_add = "\u{f211}"
    case ion_person_stalker = "\u{f212}"
    case ion_pie_graph = "\u{f2a5}"
    case ion_pin = "\u{f2a6}"
    case ion_pinpoint = "\u{f2a7}"
    case ion_pizza = "\u{f2a8}"
    case ion_plane = "\u{f214}"
    case ion_planet = "\u{f343}"
    case ion_play = "\u{f215}"
    case ion_playstation = "\u{f30a}"
    case ion_plus = "\u{f218}"
    case ion_plus_circled = "\u{f216}"
    case ion_plus_round = "\u{f217}"
    case ion_podium = "\u{f344}"
    case ion_pound = "\u{f219}"
    case ion_power = "\u{f2a9}"
    case ion_pricetag = "\u{f2aa}"
    case ion_pricetags = "\u{f2ab}"
    case ion_printer = "\u{f21a}"
    case ion_pull_request = "\u{f345}"
    case ion_qr_scanner = "\u{f346}"
    case ion_quote = "\u{f347}"
    case ion_radio_waves = "\u{f2ac}"
    case ion_record = "\u{f21b}"
    case ion_refresh = "\u{f21c}"
    case ion_reply = "\u{f21e}"
    case ion_reply_all = "\u{f21d}"
    case ion_ribbon_a = "\u{f348}"
    case ion_ribbon_b = "\u{f349}"
    case ion_sad = "\u{f34a}"
    case ion_sad_outline = "\u{f4d7}"
    case ion_scissors = "\u{f34b}"
    case ion_search = "\u{f21f}"
    case ion_settings = "\u{f2ad}"
    case ion_share = "\u{f220}"
    case ion_shuffle = "\u{f221}"
    case ion_skip_backward = "\u{f222}"
    case ion_skip_forward = "\u{f223}"
    case ion_social_android = "\u{f225}"
    case ion_social_android_outline = "\u{f224}"
    case ion_social_angular = "\u{f4d9}"
    case ion_social_angular_outline = "\u{f4d8}"
    case ion_social_apple = "\u{f227}"
    case ion_social_apple_outline = "\u{f226}"
    case ion_social_bitcoin = "\u{f2af}"
    case ion_social_bitcoin_outline = "\u{f2ae}"
    case ion_social_buffer = "\u{f229}"
    case ion_social_buffer_outline = "\u{f228}"
    case ion_social_chrome = "\u{f4db}"
    case ion_social_chrome_outline = "\u{f4da}"
    case ion_social_codepen = "\u{f4dd}"
    case ion_social_codepen_outline = "\u{f4dc}"
    case ion_social_css3 = "\u{f4df}"
    case ion_social_css3_outline = "\u{f4de}"
    case ion_social_designernews = "\u{f22b}"
    case ion_social_designernews_outline = "\u{f22a}"
    case ion_social_dribbble = "\u{f22d}"
    case ion_social_dribbble_outline = "\u{f22c}"
    case ion_social_dropbox = "\u{f22f}"
    case ion_social_dropbox_outline = "\u{f22e}"
    case ion_social_euro = "\u{f4e1}"
    case ion_social_euro_outline = "\u{f4e0}"
    case ion_social_facebook = "\u{f231}"
    case ion_social_facebook_outline = "\u{f230}"
    case ion_social_foursquare = "\u{f34d}"
    case ion_social_foursquare_outline = "\u{f34c}"
    case ion_social_freebsd_devil = "\u{f2c4}"
    case ion_social_github = "\u{f233}"
    case ion_social_github_outline = "\u{f232}"
    case ion_social_google = "\u{f34f}"
    case ion_social_google_outline = "\u{f34e}"
    case ion_social_googleplus = "\u{f235}"
    case ion_social_googleplus_outline = "\u{f234}"
    case ion_social_hackernews = "\u{f237}"
    case ion_social_hackernews_outline = "\u{f236}"
    case ion_social_html5 = "\u{f4e3}"
    case ion_social_html5_outline = "\u{f4e2}"
    case ion_social_instagram = "\u{f351}"
    case ion_social_instagram_outline = "\u{f350}"
    case ion_social_javascript = "\u{f4e5}"
    case ion_social_javascript_outline = "\u{f4e4}"
    case ion_social_linkedin = "\u{f239}"
    case ion_social_linkedin_outline = "\u{f238}"
    case ion_social_markdown = "\u{f4e6}"
    case ion_social_nodejs = "\u{f4e7}"
    case ion_social_octocat = "\u{f4e8}"
    case ion_social_pinterest = "\u{f2b1}"
    case ion_social_pinterest_outline = "\u{f2b0}"
    case ion_social_python = "\u{f4e9}"
    case ion_social_reddit = "\u{f23b}"
    case ion_social_reddit_outline = "\u{f23a}"
    case ion_social_rss = "\u{f23d}"
    case ion_social_rss_outline = "\u{f23c}"
    case ion_social_sass = "\u{f4ea}"
    case ion_social_skype = "\u{f23f}"
    case ion_social_skype_outline = "\u{f23e}"
    case ion_social_snapchat = "\u{f4ec}"
    case ion_social_snapchat_outline = "\u{f4eb}"
    case ion_social_tumblr = "\u{f241}"
    case ion_social_tumblr_outline = "\u{f240}"
    case ion_social_tux = "\u{f2c5}"
    case ion_social_twitch = "\u{f4ee}"
    case ion_social_twitch_outline = "\u{f4ed}"
    case ion_social_twitter = "\u{f243}"
    case ion_social_twitter_outline = "\u{f242}"
    case ion_social_usd = "\u{f353}"
    case ion_social_usd_outline = "\u{f352}"
    case ion_social_vimeo = "\u{f245}"
    case ion_social_vimeo_outline = "\u{f244}"
    case ion_social_whatsapp = "\u{f4f0}"
    case ion_social_whatsapp_outline = "\u{f4ef}"
    case ion_social_windows = "\u{f247}"
    case ion_social_windows_outline = "\u{f246}"
    case ion_social_wordpress = "\u{f249}"
    case ion_social_wordpress_outline = "\u{f248}"
    case ion_social_yahoo = "\u{f24b}"
    case ion_social_yahoo_outline = "\u{f24a}"
    case ion_social_yen = "\u{f4f2}"
    case ion_social_yen_outline = "\u{f4f1}"
    case ion_social_youtube = "\u{f24d}"
    case ion_social_youtube_outline = "\u{f24c}"
    case ion_soup_can = "\u{f4f4}"
    case ion_soup_can_outline = "\u{f4f3}"
    case ion_speakerphone = "\u{f2b2}"
    case ion_speedometer = "\u{f2b3}"
    case ion_spoon = "\u{f2b4}"
    case ion_star = "\u{f24e}"
    case ion_stats_bars = "\u{f2b5}"
    case ion_steam = "\u{f30b}"
    case ion_stop = "\u{f24f}"
    case ion_thermometer = "\u{f2b6}"
    case ion_thumbsdown = "\u{f250}"
    case ion_thumbsup = "\u{f251}"
    case ion_toggle = "\u{f355}"
    case ion_toggle_filled = "\u{f354}"
    case ion_transgender = "\u{f4f5}"
    case ion_trash_a = "\u{f252}"
    case ion_trash_b = "\u{f253}"
    case ion_trophy = "\u{f356}"
    case ion_tshirt = "\u{f4f7}"
    case ion_tshirt_outline = "\u{f4f6}"
    case ion_umbrella = "\u{f2b7}"
    case ion_university = "\u{f357}"
    case ion_unlocked = "\u{f254}"
    case ion_upload = "\u{f255}"
    case ion_usb = "\u{f2b8}"
    case ion_videocamera = "\u{f256}"
    case ion_volume_high = "\u{f257}"
    case ion_volume_low = "\u{f258}"
    case ion_volume_medium = "\u{f259}"
    case ion_volume_mute = "\u{f25a}"
    case ion_wand = "\u{f358}"
    case ion_waterdrop = "\u{f25b}"
    case ion_wifi = "\u{f25c}"
    case ion_wineglass = "\u{f2b9}"
    case ion_woman = "\u{f25d}"
    case ion_wrench = "\u{f2ba}"
    case ion_xbox = "\u{f30c}"
}
